on: [push, workflow_dispatch]
name: x86-64 CD Image
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Clone Kuroko
        uses: actions/checkout@v4
        with:
          repository: kuroko-lang/kuroko
          path: kuroko
      - name: Clone Bim
        uses: actions/checkout@v4
        with:
          repository: klange/bim
          path: bim
      - name: Set Execute Permissions
        run: find . -name "*.sh" -exec chmod +x {} \;
      - name: Pull Builder Image
        run: docker pull toaruos/build-tools:1.99.x
      - name: Run Builder
        run: docker run -v ${GITHUB_WORKSPACE}:/root/misaka -w /root/misaka -e LANG=C.UTF-8 -t toaruos/build-tools:1.99.x bash util/build-in-docker.sh
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: image.iso
          path: image.iso
